name: mdw
description: "Fast, Reliable, and Secure Medicine Delivery App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  lottie:
  smooth_page_indicator:
  email_validator:
  pinput:
  animations:
  #  currency_formatter:
  intl:
  permission_handler:
  shared_preferences: ^2.5.3
  flutter_native_splash:
  flutter_launcher_icons:
  #  geolocator:
  #  geocoding:
  url_launcher:
  image_picker:
  #  camera:
  http:
  #  win32: ^5.5.3
  flutter_svg:
  dotted_border: ^2.1.0
  file_picker:
  #  flutter_pdfview:
  #  native_exif:
  provider:
  connectivity_plus:
  geolocator:
  google_maps_flutter:
  flutter_polyline_points:
  location:
  geocoding:
  flutter_compass:
  qr_flutter:
#  pdf_render: ^1.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/app_icon.png"
  android_12:
    color: "#FFFFFF" # Explicitly set background color for Android 12+
    # icon_background_color: "#FFFFFF" # Optional, if your image has a transparent background

flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/feedback-emojis/
    - assets/feedback-emojis/colored/
    - assets/feedback-emojis/raw/
